import { FLOOR_HEIGHT, FLOOR_Y } from '../MapSchema.js';
import { createCoverZone, createEntrance, createFloor, createPOI, createVerticalConnector, size3, vec3, } from '../POIFactory.js';
import { createLootZone } from '../LootZoneFactory.js';
import { alleyShortcut, createTraversalLink, rampLink, rooftopBridge, undergroundTunnel } from '../TraversalFactory.js';
const aptStairs = [
    createVerticalConnector({
        id: 'apt_stairs_ground_to_second',
        type: 'stairs',
        fromFloor: 'ground',
        toFloor: 'second',
        start: vec3(-25, FLOOR_Y.ground, -7),
        end: vec3(-21, FLOOR_Y.second, -3),
        width: 1.6,
        riskLevel: 3,
        visibility: 'limited',
        gameplayNotes: 'Primary vertical route; noisy but protected from long exterior sightlines.',
    }),
    createVerticalConnector({
        id: 'apt_stairs_second_to_third',
        type: 'stairs',
        fromFloor: 'second',
        toFloor: 'third',
        start: vec3(-21, FLOOR_Y.second, -3),
        end: vec3(-25, FLOOR_Y.third, 1),
        width: 1.6,
        riskLevel: 4,
        visibility: 'limited',
        gameplayNotes: 'Choke point before roof control; defenders can hold the landing.',
    }),
    createVerticalConnector({
        id: 'apt_stairs_third_to_rooftop',
        type: 'stairs',
        fromFloor: 'third',
        toFloor: 'rooftop',
        start: vec3(-25, FLOOR_Y.third, 1),
        end: vec3(-21, FLOOR_Y.rooftop, 5),
        width: 1.4,
        riskLevel: 5,
        visibility: 'exposed',
        gameplayNotes: 'Exits onto a dangerous rooftop with strong visibility across the plaza.',
    }),
];
const garageRamps = [
    createVerticalConnector({
        id: 'garage_ramp_ground_to_second',
        type: 'ramp',
        fromFloor: 'ground',
        toFloor: 'second',
        start: vec3(20, FLOOR_Y.ground, -12),
        end: vec3(28, FLOOR_Y.second, -7),
        width: 3,
        riskLevel: 3,
        visibility: 'open',
        gameplayNotes: 'Vehicle-width ramp creates a broad combat lane between levels.',
    }),
    createVerticalConnector({
        id: 'garage_ramp_second_to_third',
        type: 'ramp',
        fromFloor: 'second',
        toFloor: 'third',
        start: vec3(28, FLOOR_Y.second, -7),
        end: vec3(20, FLOOR_Y.third, -2),
        width: 3,
        riskLevel: 4,
        visibility: 'exposed',
        gameplayNotes: 'Upper ramp creates a readable cross-level firing lane.',
    }),
    createVerticalConnector({
        id: 'garage_ramp_third_to_roof',
        type: 'ramp',
        fromFloor: 'third',
        toFloor: 'rooftop',
        start: vec3(20, FLOOR_Y.third, -2),
        end: vec3(28, FLOOR_Y.rooftop, -7),
        width: 3,
        riskLevel: 5,
        visibility: 'exposed',
        gameplayNotes: 'Final roof ramp is visible from the market and sniper perch.',
    }),
];
const traversalLinks = [
    rooftopBridge({
        id: 'apt_roof_to_sniper_bridge',
        fromPOI: 'poi_apartment_block',
        toPOI: 'poi_rooftop_perch',
        fromFloor: 'rooftop',
        toFloor: 'rooftop',
        start: vec3(-18, FLOOR_Y.rooftop, 6),
        end: vec3(-5, FLOOR_Y.rooftop, 8),
        riskLevel: 5,
        visibility: 'exposed',
        gameplayNotes: 'Fast high-ground bridge with huge sightlines and almost no cover.',
    }),
    rooftopBridge({
        id: 'garage_roof_to_perch_bridge',
        fromPOI: 'poi_parking_garage',
        toPOI: 'poi_rooftop_perch',
        fromFloor: 'rooftop',
        toFloor: 'rooftop',
        start: vec3(18, FLOOR_Y.rooftop, -2),
        end: vec3(4, FLOOR_Y.rooftop, 6),
        riskLevel: 5,
        visibility: 'exposed',
        gameplayNotes: 'Alternate sniper rotation; powerful but readable from the plaza.',
    }),
    undergroundTunnel({
        id: 'warehouse_to_garage_tunnel',
        fromPOI: 'poi_warehouse',
        toPOI: 'poi_underground_tunnel',
        fromFloor: 'ground',
        toFloor: 'underground',
        start: vec3(6, FLOOR_Y.ground, 24),
        end: vec3(10, FLOOR_Y.underground, 12),
        riskLevel: 2,
        visibility: 'hidden',
        gameplayNotes: 'Safer rotation away from rooftops; exits are predictable and easy to trap.',
    }),
    undergroundTunnel({
        id: 'tunnel_to_garage_exit',
        fromPOI: 'poi_underground_tunnel',
        toPOI: 'poi_parking_garage',
        fromFloor: 'underground',
        toFloor: 'ground',
        start: vec3(16, FLOOR_Y.underground, 4),
        end: vec3(23, FLOOR_Y.ground, -10),
        riskLevel: 3,
        visibility: 'limited',
        gameplayNotes: 'Tunnel exit opens under the garage ramp, enabling flank plays.',
    }),
    alleyShortcut({
        id: 'market_to_warehouse_alley',
        fromPOI: 'poi_market',
        toPOI: 'poi_warehouse',
        fromFloor: 'ground',
        toFloor: 'ground',
        start: vec3(-8, FLOOR_Y.ground, 4),
        end: vec3(-5, FLOOR_Y.ground, 20),
        riskLevel: 4,
        visibility: 'limited',
        gameplayNotes: 'Short ambush route with broken sightlines and weak loot.',
    }),
    alleyShortcut({
        id: 'alley_to_plaza_cut',
        fromPOI: 'poi_alley',
        toPOI: 'poi_plaza',
        fromFloor: 'ground',
        toFloor: 'ground',
        start: vec3(-8, FLOOR_Y.ground, 2),
        end: vec3(-2, FLOOR_Y.ground, -2),
        riskLevel: 3,
        visibility: 'limited',
        gameplayNotes: 'Lets players break contact from market fights into the central plaza.',
    }),
    rampLink({
        id: 'garage_street_ramp_entry',
        fromPOI: 'poi_plaza',
        toPOI: 'poi_parking_garage',
        fromFloor: 'ground',
        toFloor: 'ground',
        start: vec3(9, FLOOR_Y.ground, -5),
        end: vec3(17, FLOOR_Y.ground, -10),
        riskLevel: 3,
        visibility: 'open',
        gameplayNotes: 'Main street approach into the parking garage; supports vehicle-cover fights.',
    }),
    createTraversalLink({
        id: 'shack_to_locked_room_lane',
        type: 'alley_shortcut',
        fromPOI: 'poi_loot_shack',
        toPOI: 'poi_locked_loot_room',
        fromFloor: 'ground',
        toFloor: 'ground',
        start: vec3(-28, FLOOR_Y.ground, -22),
        end: vec3(-11, FLOOR_Y.ground, -23),
        riskLevel: 4,
        visibility: 'open',
        gameplayNotes: 'Tempting loot-to-vault run across exposed street space.',
    }),
];
export const DistrictMap01 = {
    id: 'district_map_01',
    name: 'District Map 01 - Vertical Blockout',
    bounds: { min: vec3(-45, -6, -45), max: vec3(45, FLOOR_Y.rooftop + 6, 45) },
    floorHeight: FLOOR_HEIGHT,
    notes: 'Semantic multiplayer district blockout. Ground is y=0, upper floors are 5m increments, rooftop is y=15, tunnel level is y=-5.',
    traversalLinks,
    pois: [
        createPOI({
            id: 'poi_apartment_block',
            name: 'Signal Apartments',
            category: 'apartment_block',
            position: vec3(-25, 0, 0),
            size: size3(14, 15, 12),
            dangerLevel: 4,
            gameplayPurpose: 'Dense vertical combat, rooftop access, and mid-tier residential loot.',
            floors: [
                createFloor('ground', 'Ground Floor', FLOOR_Y.ground, size3(14, 0.18, 12), 'Entry fights and lobby cover.'),
                createFloor('second', 'Second Floor', FLOOR_Y.second, size3(13, 0.18, 11), 'Apartment-to-apartment midline duels.'),
                createFloor('third', 'Third Floor', FLOOR_Y.third, size3(12, 0.18, 10), 'Pre-roof staging floor with riskier loot.'),
                createFloor('rooftop', 'Rooftop', FLOOR_Y.rooftop, size3(13, 0.18, 11), 'High-ground rotation and exposed overwatch.'),
            ],
            entrances: [
                createEntrance({ id: 'apt_front_door', floor: 'ground', position: vec3(-25, 0, -6.2), width: 2.2, direction: vec3(0, 0, -1), gameplayNotes: 'Main public entry from plaza.' }),
                createEntrance({ id: 'apt_back_door', floor: 'ground', position: vec3(-31.8, 0, 3), width: 1.4, direction: vec3(-1, 0, 0), gameplayNotes: 'Side exit toward loot shack lane.' }),
            ],
            stairs: aptStairs,
            ladders: [
                createVerticalConnector({
                    id: 'apt_fire_escape_ladder',
                    type: 'ladder',
                    fromFloor: 'ground',
                    toFloor: 'third',
                    start: vec3(-32.4, FLOOR_Y.ground, 5),
                    end: vec3(-32.4, FLOOR_Y.third, 5),
                    riskLevel: 4,
                    visibility: 'exposed',
                    gameplayNotes: 'Fast flank up the exterior wall, but visible from shack street.',
                }),
            ],
            lootZones: [
                createLootZone({ id: 'apt_lobby_loot', position: vec3(-22, 0, -3), size: size3(3, 1, 2), lootTier: 'common', spawnChance: 0.8, containerCount: 2, gameplayNotes: 'Low-value entry loot to pull players into the building.' }),
                createLootZone({ id: 'apt_roof_cache', position: vec3(-28, FLOOR_Y.rooftop, 3), size: size3(3, 1, 2), lootTier: 'rare', spawnChance: 0.55, containerCount: 2, isHidden: true, gameplayNotes: 'Hidden rooftop cache rewards exposed climbing.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'apt_lobby_wall', position: vec3(-26, 0, -2), size: size3(5, 1, 0.4), coverType: 'interior_wall', height: 1.6, direction: vec3(0, 0, 1), gameplayPurpose: 'Breaks up lobby sightline.' }),
                createCoverZone({ id: 'apt_roof_ac', position: vec3(-23, FLOOR_Y.rooftop, 3), size: size3(2.2, 1, 1.4), coverType: 'rooftop_ac_unit', height: 1.2, direction: vec3(1, 0, 0), gameplayPurpose: 'Only rooftop cover, forcing risky peeks.' }),
            ],
            traversalLinks: ['apt_roof_to_sniper_bridge'],
            lightingMood: 'shadowed',
            notes: 'Three-floor block with explicit y=0,5,10,15 walkable levels.',
        }),
        createPOI({
            id: 'poi_warehouse',
            name: 'North Loading Warehouse',
            category: 'warehouse',
            position: vec3(0, 0, 24),
            size: size3(24, 10, 14),
            dangerLevel: 3,
            gameplayPurpose: 'Medium-risk loot with open sightlines and a mezzanine angle.',
            floors: [
                createFloor('ground', 'Warehouse Floor', FLOOR_Y.ground, size3(24, 0.18, 14), 'Open combat floor with containers.'),
                createFloor('second', 'Mezzanine', FLOOR_Y.second, size3(16, 0.18, 6), 'Overlook above interior loot.'),
            ],
            entrances: [
                createEntrance({ id: 'warehouse_loading_door', floor: 'ground', position: vec3(0, 0, 16.8), width: 4, direction: vec3(0, 0, -1), gameplayNotes: 'Wide loading entrance favors crossfire.' }),
                createEntrance({ id: 'warehouse_tunnel_hatch', floor: 'ground', position: vec3(6, 0, 24), width: 1.4, direction: vec3(1, 0, 0), gameplayNotes: 'Hidden hatch to tunnel rotation.' }),
            ],
            stairs: [
                createVerticalConnector({ id: 'warehouse_mezz_stairs', type: 'stairs', fromFloor: 'ground', toFloor: 'second', start: vec3(-9, 0, 21), end: vec3(-4, 5, 24), width: 1.8, riskLevel: 3, visibility: 'open', gameplayNotes: 'Visible stair up to mezzanine.' }),
            ],
            lootZones: [
                createLootZone({ id: 'warehouse_floor_loot', position: vec3(4, 0, 22), size: size3(5, 1, 4), lootTier: 'uncommon', spawnChance: 0.75, containerCount: 4, gameplayNotes: 'Medium reward in open space.' }),
                createLootZone({ id: 'warehouse_mezz_cache', position: vec3(-2, 5, 25), size: size3(4, 1, 2), lootTier: 'rare', spawnChance: 0.45, containerCount: 2, gameplayNotes: 'Mezzanine loot is safer once controlled.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'warehouse_container_cover_a', position: vec3(6, 0, 27), size: size3(5, 1, 1.2), coverType: 'crate_stack', height: 1.8, direction: vec3(0, 0, -1), gameplayPurpose: 'Breaks open warehouse lanes.' }),
                createCoverZone({ id: 'warehouse_interior_wall', position: vec3(-7, 0, 22), size: size3(0.5, 1, 5), coverType: 'interior_wall', height: 2.2, direction: vec3(1, 0, 0), gameplayPurpose: 'Creates a left-side flank lane.' }),
            ],
            traversalLinks: ['warehouse_to_garage_tunnel', 'market_to_warehouse_alley'],
            lightingMood: 'industrial',
            notes: 'Two distinct walkable levels at y=0 and y=5.',
        }),
        createPOI({
            id: 'poi_market',
            name: 'Canopy Market',
            category: 'market',
            position: vec3(-2, 0, 4),
            size: size3(18, 2, 12),
            dangerLevel: 2,
            gameplayPurpose: 'Close-range cover maze with weaker loot and many ambush breaks.',
            floors: [createFloor('ground', 'Market Street', FLOOR_Y.ground, size3(18, 0.18, 12), 'Low cover trading space.')],
            entrances: [
                createEntrance({ id: 'market_plaza_entry', floor: 'ground', position: vec3(0, 0, -2), width: 5, direction: vec3(0, 0, -1), gameplayNotes: 'Wide public entry from plaza.' }),
            ],
            lootZones: [
                createLootZone({ id: 'market_vendor_loot', position: vec3(-2, 0, 5), size: size3(4, 1, 3), lootTier: 'common', spawnChance: 0.9, containerCount: 3, gameplayNotes: 'Common supplies spread between stalls.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'market_stalls_west', position: vec3(-7, 0, 4), size: size3(5, 1, 1.5), coverType: 'market_stall', height: 1.4, direction: vec3(1, 0, 0), gameplayPurpose: 'Stall cover for short rotations.' }),
                createCoverZone({ id: 'market_stalls_east', position: vec3(5, 0, 7), size: size3(5, 1, 1.5), coverType: 'market_stall', height: 1.4, direction: vec3(-1, 0, 0), gameplayPurpose: 'Counter-cover facing the plaza.' }),
                createCoverZone({ id: 'market_crate_stack', position: vec3(0, 0, 0), size: size3(2.5, 1, 2), coverType: 'crate_stack', height: 1.8, direction: vec3(0, 0, 1), gameplayPurpose: 'Central ambush divider.' }),
            ],
            traversalLinks: ['market_to_warehouse_alley'],
            lightingMood: 'neon',
            notes: 'Ground-only POI intentionally rich in cover and weak in loot.',
        }),
        createPOI({
            id: 'poi_parking_garage',
            name: 'East Parking Garage',
            category: 'parking_garage',
            position: vec3(24, 0, -8),
            size: size3(18, 15, 18),
            dangerLevel: 4,
            gameplayPurpose: 'Vertical combat arena with ramps, cars as cover, and tunnel exit pressure.',
            floors: [
                createFloor('ground', 'Garage Ground', FLOOR_Y.ground, size3(18, 0.18, 18), 'Street entry and tunnel exit fights.'),
                createFloor('second', 'Garage Level 2', FLOOR_Y.second, size3(18, 0.18, 18), 'Mid-level ramp combat.'),
                createFloor('third', 'Garage Level 3', FLOOR_Y.third, size3(18, 0.18, 18), 'Upper combat deck with long ramp sightlines.'),
                createFloor('rooftop', 'Garage Roof', FLOOR_Y.rooftop, size3(18, 0.18, 18), 'High ground connected to sniper perch.'),
            ],
            entrances: [
                createEntrance({ id: 'garage_street_entry', floor: 'ground', position: vec3(16, 0, -10), width: 5, direction: vec3(-1, 0, 0), gameplayNotes: 'Main vehicle ramp entry.' }),
                createEntrance({ id: 'garage_tunnel_exit', floor: 'ground', position: vec3(23, 0, -16.8), width: 2, direction: vec3(0, 0, -1), gameplayNotes: 'Tunnel exit under ramp.' }),
            ],
            ramps: garageRamps,
            ladders: [
                createVerticalConnector({ id: 'garage_service_ladder', type: 'ladder', fromFloor: 'ground', toFloor: 'rooftop', start: vec3(32, 0, -16), end: vec3(32, 15, -16), riskLevel: 4, visibility: 'exposed', gameplayNotes: 'Fast exterior climb, highly visible.' }),
            ],
            elevators: [
                createVerticalConnector({ id: 'garage_broken_lift', type: 'elevator', fromFloor: 'ground', toFloor: 'second', start: vec3(18, 0, -2), end: vec3(18, 5, -2), riskLevel: 3, visibility: 'limited', gameplayNotes: 'Slow utility lift placeholder for future interaction.' }),
            ],
            lootZones: [
                createLootZone({ id: 'garage_mid_cache', position: vec3(28, 5, -10), size: size3(4, 1, 3), lootTier: 'uncommon', spawnChance: 0.6, containerCount: 2, gameplayNotes: 'Moderate reward in contested mid-level.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'garage_vehicle_cover_a', position: vec3(22, 0, -11), size: size3(3, 1, 1.6), coverType: 'vehicle', height: 1.4, direction: vec3(0, 0, 1), gameplayPurpose: 'Car cover on entry lane.' }),
                createCoverZone({ id: 'garage_roof_barrier', position: vec3(24, 15, -1), size: size3(8, 1, 0.8), coverType: 'concrete_barrier', height: 1.1, direction: vec3(0, 0, -1), gameplayPurpose: 'Roofline cover for bridge fights.' }),
            ],
            traversalLinks: ['garage_roof_to_perch_bridge', 'tunnel_to_garage_exit', 'garage_street_ramp_entry'],
            lightingMood: 'high_contrast',
            notes: 'Parking garage floors use y=0, y=5, y=10, and y=15 with a ramp between every level.',
        }),
        createPOI({
            id: 'poi_rooftop_perch',
            name: 'Billboard Perch',
            category: 'rooftop_perch',
            position: vec3(0, 15, 7),
            size: size3(9, 2, 7),
            dangerLevel: 5,
            gameplayPurpose: 'Powerful overwatch that is visible and exposed from multiple rotations.',
            floors: [createFloor('rooftop', 'Sniper Platform', FLOOR_Y.rooftop, size3(9, 0.18, 7), 'High-risk, high-visibility perch.')],
            entrances: [
                createEntrance({ id: 'perch_bridge_west', floor: 'rooftop', position: vec3(-4.8, 15, 7), width: 2, direction: vec3(-1, 0, 0), gameplayNotes: 'Bridge from apartment roof.' }),
                createEntrance({ id: 'perch_bridge_east', floor: 'rooftop', position: vec3(4.8, 15, 7), width: 2, direction: vec3(1, 0, 0), gameplayNotes: 'Bridge from garage roof.' }),
            ],
            lootZones: [
                createLootZone({ id: 'perch_weapon_case', position: vec3(0, 15, 8), size: size3(2, 1, 1.5), lootTier: 'rare', spawnChance: 0.35, containerCount: 1, gameplayNotes: 'Single contested weapon case.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'perch_billboard_backstop', position: vec3(0, 15, 10), size: size3(8, 1, 0.5), coverType: 'low_wall', height: 1.4, direction: vec3(0, 0, -1), gameplayPurpose: 'Backstop prevents perch from being pure deathtrap.' }),
            ],
            traversalLinks: ['apt_roof_to_sniper_bridge', 'garage_roof_to_perch_bridge'],
            lightingMood: 'daylit',
            notes: 'High ground has strong vision, thin cover, and two exposed bridge routes.',
        }),
        createPOI({
            id: 'poi_underground_tunnel',
            name: 'Service Tunnel',
            category: 'underground_tunnel',
            position: vec3(12, -5, 6),
            size: size3(18, 2.5, 8),
            dangerLevel: 2,
            gameplayPurpose: 'Safer rotation with poor visibility, limited exits, and ambush risk.',
            floors: [createFloor('underground', 'Tunnel Level', FLOOR_Y.underground, size3(18, 0.18, 8), 'Lowered y=-5 walkable tunnel path.')],
            entrances: [
                createEntrance({ id: 'tunnel_warehouse_hatch', floor: 'underground', position: vec3(10, -5, 12), width: 1.5, direction: vec3(0, 0, 1), gameplayNotes: 'Hatch under warehouse.' }),
                createEntrance({ id: 'tunnel_garage_exit', floor: 'underground', position: vec3(16, -5, 2), width: 1.5, direction: vec3(1, 0, 0), gameplayNotes: 'Exit toward garage.' }),
            ],
            lootZones: [
                createLootZone({ id: 'tunnel_hidden_bag', position: vec3(12, -5, 6), size: size3(2, 1, 1.5), lootTier: 'uncommon', spawnChance: 0.4, containerCount: 1, isHidden: true, gameplayNotes: 'Hidden bag for attentive tunnel players.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'tunnel_pipe_cover', position: vec3(14, -5, 7), size: size3(4, 1, 0.8), coverType: 'low_wall', height: 0.9, direction: vec3(0, 0, -1), gameplayPurpose: 'Pipe cover in tight tunnel fights.' }),
            ],
            traversalLinks: ['warehouse_to_garage_tunnel', 'tunnel_to_garage_exit'],
            lightingMood: 'underground',
            notes: 'This POI is physically below the map at y=-5, not just dark-colored ground.',
        }),
        createPOI({
            id: 'poi_loot_shack',
            name: 'Southwest Loot Shack',
            category: 'loot_shack',
            position: vec3(-31, 0, -24),
            size: size3(7, 3, 6),
            dangerLevel: 2,
            gameplayPurpose: 'Small early-route loot stop with one vulnerable exit.',
            floors: [createFloor('ground', 'Shack Floor', FLOOR_Y.ground, size3(7, 0.18, 6), 'Compact loot room.')],
            entrances: [
                createEntrance({ id: 'shack_front', floor: 'ground', position: vec3(-31, 0, -20.8), width: 1.4, direction: vec3(0, 0, 1), gameplayNotes: 'Single obvious entrance.' }),
            ],
            lootZones: [
                createLootZone({ id: 'shack_supplies', position: vec3(-31, 0, -24), size: size3(3, 1, 2), lootTier: 'uncommon', spawnChance: 0.7, containerCount: 2, gameplayNotes: 'Reliable but not premium loot.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'shack_crates', position: vec3(-34, 0, -23), size: size3(2, 1, 2), coverType: 'crate_stack', height: 1.5, direction: vec3(1, 0, 0), gameplayPurpose: 'Exterior cover before committing inside.' }),
            ],
            traversalLinks: ['shack_to_locked_room_lane'],
            lightingMood: 'shadowed',
            notes: 'Simple low-tier loot POI for early rotations.',
        }),
        createPOI({
            id: 'poi_locked_loot_room',
            name: 'Keycard Vault',
            category: 'locked_loot_room',
            position: vec3(-9, 0, -24),
            size: size3(8, 4, 7),
            dangerLevel: 5,
            gameplayPurpose: 'High-risk locked room with superior loot and a loud approach.',
            floors: [createFloor('ground', 'Vault Floor', FLOOR_Y.ground, size3(8, 0.18, 7), 'Locked high-value room.')],
            entrances: [
                createEntrance({ id: 'vault_keycard_door', floor: 'ground', position: vec3(-9, 0, -20.4), width: 1.6, direction: vec3(0, 0, 1), isLocked: true, requiredKeyId: 'key_vault_01', gameplayNotes: 'Requires keycard and exposes player from plaza edge.' }),
            ],
            lootZones: [
                createLootZone({ id: 'vault_epic_case', position: vec3(-10, 0, -24), size: size3(3, 1, 2), lootTier: 'epic', spawnChance: 0.85, containerCount: 2, isLocked: true, requiredKeyId: 'key_vault_01', gameplayNotes: 'Best consistent loot in the district.' }),
                createLootZone({ id: 'vault_legendary_roll', position: vec3(-6.5, 0, -24), size: size3(2, 1, 2), lootTier: 'legendary', spawnChance: 0.18, containerCount: 1, isHidden: true, isLocked: true, requiredKeyId: 'key_vault_01', gameplayNotes: 'Rare jackpot spawn for key holders.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'vault_interior_wall', position: vec3(-9, 0, -26.5), size: size3(6, 1, 0.4), coverType: 'interior_wall', height: 1.8, direction: vec3(0, 0, 1), gameplayPurpose: 'Interior cover prevents doorway instant wins.' }),
            ],
            traversalLinks: ['shack_to_locked_room_lane'],
            lightingMood: 'high_contrast',
            notes: 'Locked loot room intentionally draws players into high-risk street exposure.',
        }),
        createPOI({
            id: 'poi_alley',
            name: 'Knife Alley',
            category: 'alley',
            position: vec3(-8, 0, 8),
            size: size3(4, 2, 18),
            dangerLevel: 4,
            gameplayPurpose: 'Ambush shortcut between market, warehouse, and plaza.',
            floors: [createFloor('ground', 'Alley Ground', FLOOR_Y.ground, size3(4, 0.18, 18), 'Narrow shortcut route.')],
            entrances: [
                createEntrance({ id: 'alley_market_mouth', floor: 'ground', position: vec3(-8, 0, 2), width: 2, direction: vec3(0, 0, -1), gameplayNotes: 'Market-side mouth.' }),
                createEntrance({ id: 'alley_warehouse_mouth', floor: 'ground', position: vec3(-5, 0, 18), width: 2, direction: vec3(0, 0, 1), gameplayNotes: 'Warehouse-side mouth.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'alley_dumpster_cover', position: vec3(-9, 0, 9), size: size3(2, 1, 1.4), coverType: 'crate_stack', height: 1.4, direction: vec3(1, 0, 0), gameplayPurpose: 'Single ambush pocket in the shortcut.' }),
            ],
            traversalLinks: ['market_to_warehouse_alley', 'alley_to_plaza_cut'],
            lightingMood: 'shadowed',
            notes: 'Short route with limited visibility and strong ambush risk.',
        }),
        createPOI({
            id: 'poi_plaza',
            name: 'Central Plaza',
            category: 'plaza',
            position: vec3(5, 0, -4),
            size: size3(20, 1, 16),
            dangerLevel: 3,
            gameplayPurpose: 'Central intersection tying market, garage, apartments, and vault routes together.',
            floors: [createFloor('ground', 'Street Level', FLOOR_Y.ground, size3(20, 0.18, 16), 'Main rotation intersection.')],
            entrances: [
                createEntrance({ id: 'plaza_west_entry', floor: 'ground', position: vec3(-5, 0, -4), width: 5, direction: vec3(-1, 0, 0), gameplayNotes: 'Toward apartments and market.' }),
                createEntrance({ id: 'plaza_east_entry', floor: 'ground', position: vec3(15, 0, -4), width: 5, direction: vec3(1, 0, 0), gameplayNotes: 'Toward parking garage.' }),
            ],
            lootZones: [
                createLootZone({ id: 'plaza_common_crate', position: vec3(4, 0, -7), size: size3(2, 1, 2), lootTier: 'common', spawnChance: 0.5, containerCount: 1, gameplayNotes: 'Small bait crate in exposed center.' }),
            ],
            coverZones: [
                createCoverZone({ id: 'plaza_low_wall_north', position: vec3(4, 0, 0), size: size3(8, 1, 0.7), coverType: 'low_wall', height: 1.0, direction: vec3(0, 0, -1), gameplayPurpose: 'Partial cover without fully blocking sightlines.' }),
                createCoverZone({ id: 'plaza_vehicle_cover', position: vec3(10, 0, -8), size: size3(3.5, 1, 1.8), coverType: 'vehicle', height: 1.4, direction: vec3(-1, 0, 0), gameplayPurpose: 'Garage approach cover.' }),
            ],
            traversalLinks: ['alley_to_plaza_cut', 'garage_street_ramp_entry'],
            lightingMood: 'daylit',
            notes: 'Central fight space. Open enough for high-ground pressure, but not empty.',
        }),
    ],
};
export default DistrictMap01;
//# sourceMappingURL=DistrictMap01.js.map